const root=document.documentElement,boot=document.querySelector('.boot'),counter=boot.querySelector('span');let n=0;const timer=setInterval(()=>{n=Math.min(100,n+Math.ceil(Math.random()*8));counter.textContent=n+'%';if(n===100){clearInterval(timer);setTimeout(()=>boot.classList.add('done'),220)}},85);
addEventListener('mousemove',e=>{root.style.setProperty('--x',((e.clientX/innerWidth)-.5)*2);root.style.setProperty('--y',((e.clientY/innerHeight)-.5)*2);root.style.setProperty('--px',e.clientX+'px');root.style.setProperty('--py',e.clientY+'px')});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.11});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const sections=[...document.querySelectorAll('section[id]')],links=[...document.querySelectorAll('.nav__links a')];addEventListener('scroll',()=>{let current='home';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))},{passive:true});
document.querySelector('.menu').addEventListener('click',()=>document.querySelector('.nav').classList.toggle('open'));links.forEach(a=>a.addEventListener('click',()=>document.querySelector('.nav').classList.remove('open')));
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.13}px,${(e.clientY-r.top-r.height/2)*.13}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});
const canvas=document.getElementById('space'),ctx=canvas.getContext('2d');let dots=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;dots=Array.from({length:Math.min(90,Math.floor(innerWidth/15))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.3+.2,v:Math.random()*.18+.03}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(93,211,195,.38)';dots.forEach(d=>{d.y-=d.v;if(d.y<0)d.y=innerHeight;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();

const rain=document.getElementById('code-rain'),rainCtx=rain.getContext('2d');let columns=[],rainW=0,rainH=0;const glyphs='01{}[]<>/=+*constfunctionreturnasyncawaitNK';function resizeRain(){const box=rain.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,2);rain.width=box.width*ratio;rain.height=box.height*ratio;rainCtx.setTransform(ratio,0,0,ratio,0,0);rainW=box.width;rainH=box.height;columns=Array.from({length:Math.ceil(rainW/20)},()=>Math.random()*-40)}function drawRain(){rainCtx.fillStyle='rgba(7,17,20,.075)';rainCtx.fillRect(0,0,rainW,rainH);rainCtx.font='10px Consolas';rainCtx.fillStyle='rgba(91,211,194,.55)';columns.forEach((y,i)=>{const char=glyphs[Math.floor(Math.random()*glyphs.length)];rainCtx.fillText(char,i*20,y*17);if(y*17>rainH&&Math.random()>.975)columns[i]=0;else columns[i]+=.22});requestAnimationFrame(drawRain)}addEventListener('resize',resizeRain);resizeRain();drawRain();

// Chrome Translator API: translations are generated on-device and never stored in the HTML.
const langWidget=document.querySelector('.language-widget'),langTrigger=document.querySelector('.language-trigger'),langLabel=langTrigger.querySelector('b'),langButtons=[...document.querySelectorAll('.language-menu button[data-lang]')],toast=document.querySelector('.translation-toast'),toastText=toast.querySelector('span');
const languageNames={ar:'العربية',en:'English',tr:'Türkçe',de:'Deutsch',fr:'Français',es:'Español'};let toastTimer;
function showToast(message,error=false){toastText.textContent=message;toast.querySelector('i').style.background=error?'#e77a67':'';toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),4200)}
langTrigger.addEventListener('click',()=>langWidget.classList.toggle('open'));document.addEventListener('click',e=>{if(!langWidget.contains(e.target))langWidget.classList.remove('open')});
const blockedTags=new Set(['SCRIPT','STYLE','CODE','PRE','CANVAS','NOSCRIPT']);const textNodes=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){const parent=node.parentElement,text=node.nodeValue.trim();if(!text||blockedTags.has(parent.tagName)||parent.closest('[data-no-translate]')||parent.closest('.brand')||parent.closest('.code-window')||parent.closest('.image-slot')||parent.closest('.boot'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});while(walker.nextNode()){const node=walker.currentNode;textNodes.push({node,original:node.nodeValue})}
function browserTranslation(target){showToast(`Loading ${languageNames[target]} translation…`);let host=document.getElementById('google_translate_element');if(!host){host=document.createElement('div');host.id='google_translate_element';host.hidden=true;document.body.appendChild(host)}const choose=()=>{const combo=document.querySelector('.goog-te-combo');if(!combo)return false;combo.value=target;combo.dispatchEvent(new Event('change',{bubbles:true}));langLabel.textContent=languageNames[target];langButtons.forEach(b=>b.classList.toggle('selected',b.dataset.lang===target));showToast(`Translated to ${languageNames[target]}`);return true};if(choose())return;window.googleTranslateElementInit=()=>{new google.translate.TranslateElement({pageLanguage:'ar',includedLanguages:'ar,en,tr,de,fr,es',autoDisplay:false},'google_translate_element');let tries=0;const timer=setInterval(()=>{if(choose()||++tries>40)clearInterval(timer)},150)};if(!document.getElementById('google-translate-script')){const script=document.createElement('script');script.id='google-translate-script';script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';script.async=true;script.onerror=()=>showToast('افتح قائمة Chrome واختر ترجمة الصفحة',true);document.head.appendChild(script)}else window.googleTranslateElementInit()}
async function setLanguage(target){langWidget.classList.remove('open');if(target==='ar'){textNodes.forEach(item=>item.node.nodeValue=item.original);document.documentElement.lang='ar';document.documentElement.dir='rtl';langLabel.textContent=languageNames.ar;langButtons.forEach(b=>b.classList.toggle('selected',b.dataset.lang==='ar'));showToast('تمت استعادة اللغة العربية');return}if(!('Translator' in self)){browserTranslation(target);return}langWidget.classList.add('translating');showToast('يتم تجهيز نموذج الترجمة داخل المتصفح…');try{const availability=await Translator.availability({sourceLanguage:'ar',targetLanguage:target});if(availability==='unavailable'){browserTranslation(target);return}const translator=await Translator.create({sourceLanguage:'ar',targetLanguage:target,monitor(m){m.addEventListener('downloadprogress',e=>showToast(`تنزيل نموذج اللغة ${Math.round(e.loaded*100)}%`))}});for(const item of textNodes){const clean=item.original.trim();if(!clean)continue;const translated=await translator.translate(clean);item.node.nodeValue=item.original.replace(clean,translated)}document.documentElement.lang=target;document.documentElement.dir=target==='ar'?'rtl':'ltr';langLabel.textContent=languageNames[target];langButtons.forEach(b=>b.classList.toggle('selected',b.dataset.lang===target));showToast(`تمت الترجمة إلى ${languageNames[target]} بواسطة AI`);translator.destroy?.()}catch(error){browserTranslation(target)}finally{langWidget.classList.remove('translating')}}
langButtons.forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));

// Match the site language to the visitor's browser/device language.
const onboarding={en:{title:'View the website in English',copy:'Your device language is different from Arabic. We can translate the website automatically on your device.',button:'Start translation',note:'The language model is downloaded only once'},tr:{title:'Web sitesini Türkçe görüntüle',copy:'Cihaz diliniz Arapçadan farklı. Web sitesini cihazınızda otomatik olarak çevirebiliriz.',button:'Çeviriyi başlat',note:'Dil modeli yalnızca bir kez indirilir'},de:{title:'Website auf Deutsch anzeigen',copy:'Ihre Gerätesprache ist nicht Arabisch. Wir können die Website automatisch auf Ihrem Gerät übersetzen.',button:'Übersetzung starten',note:'Das Sprachmodell wird nur einmal heruntergeladen'},fr:{title:'Afficher le site en français',copy:'La langue de votre appareil est différente de l’arabe. Nous pouvons traduire le site automatiquement sur votre appareil.',button:'Commencer la traduction',note:'Le modèle de langue est téléchargé une seule fois'},es:{title:'Ver el sitio en español',copy:'El idioma de tu dispositivo es diferente del árabe. Podemos traducir el sitio automáticamente en tu dispositivo.',button:'Iniciar traducción',note:'El modelo de idioma se descarga una sola vez'}};
async function autoTranslateForVisitor(){const deviceLanguage=(navigator.languages?.[0]||navigator.language||'ar').toLowerCase().split('-')[0];if(deviceLanguage==='ar')return;const target=languageNames[deviceLanguage]?deviceLanguage:'en';const prompt=document.querySelector('.auto-language-prompt'),start=prompt.querySelector('button'),ui=onboarding[target]||onboarding.en;prompt.querySelector('h3').textContent=ui.title;prompt.querySelector('p').textContent=ui.copy;start.childNodes[0].nodeValue=ui.button+' ';prompt.querySelector('small').textContent=ui.note;prompt.classList.add('show');prompt.setAttribute('aria-hidden','false');start.onclick=()=>{prompt.classList.remove('show');prompt.setAttribute('aria-hidden','true');setLanguage(target)};if(!('Translator' in self))return;try{const availability=await Translator.availability({sourceLanguage:'ar',targetLanguage:target});if(availability==='available'){prompt.classList.remove('show');prompt.setAttribute('aria-hidden','true');setLanguage(target)}}catch(error){}}
// Automatic language selection is handled by static-i18n.js.
